# Generated by Django 6.0.7 on 2026-07-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0003_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
