# Generated by Django 6.0.7 on 2026-07-31 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0004_alter_question_marks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
