# Generated by Django 6.0.7 on 2026-08-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0008_quizsettings_computersciencequestion_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
