# Generated by Django 6.0.7 on 2026-08-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0009_alter_quizattempt_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='option_a',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='option_b',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='option_c',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='option_d',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_answer',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
