# Generated by Django 6.0.7 on 2026-08-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0010_remove_useranswer_question_useranswer_option_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.TextField(default=''),
        ),
    ]
